<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Домашнее задание 2. Библиотека Numpy и линейная алгебра.
</b></h2>

---

In [0]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [0]:
import numpy as np
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?


# ========
# Ваш код здесь
print(a.ndim, a.shape)

flist = [ [1, 3, 4, 5],[1, 3, 4, 5], [1, 3, 4, 5],[1, 3, 4, 5]]

print([flist[j][2]  for j in range(len(flist))] )

# ========
print(a)
print(b)

In [6]:
import numpy as np

first = [[1, 2],
         [3, 4]]
second = [[1, 2],
          [3, 4]]

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """

    #YOUR CODE: please do not use numpy
    result = []
    sum = 0.0
    for i in range(len(first)):
        res = []
        for j in range(len(first[0])):
            for k in range(len(first[0])):
                sum += first[i][k] * second[k][j]
            res.append(sum)
            sum = 0.0
        result.append(res)
        
    return result
no_numpy_mult(first, second)


[[7.0, 10.0], [15.0, 22.0]]

In [0]:
def np_mult(a, b):
    
  
    return np.dot(a,b)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [7]:
import numpy as np

def no_numpy_scalar(v1, v2):
    sum = 0
    for i in range(3):
        sum += v1[i] * v2[i]
    return sum
    

def numpy_scalar (v1, v2):
    return np.dot(v1, v2)
v1 = [0, 1, 2]
v2 = [3, 4, 5]
print(no_numpy_scalar(v1, v2))
print(numpy_scalar(v1, v2))

14
14


In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    return np.sum(list(filter(lambda x: x % 2 == 0, np.diag(a))))

In [31]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
print (a)
np_diag_2k(a)

[[1 5 1 1 5]
 [1 1 3 3 7]
 [1 7 7 5 8]
 [3 6 3 6 8]
 [1 8 1 5 8]]


14

In [0]:
np.sum(list(filter(lambda x: x % 2 == 0, np.diag(a))))

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [0]:
import numpy as np

def cumsum(A):
    return np.array([np.cumsum(A[i]) for i in range(A.shape[0])])
    

In [35]:
X = np.array([[1, 2, 2],
              [3, 3, 1],
              [1, 5, 5],
              [2, 3, 3]])
print(cumsum(X))

[[ 1  3  5]
 [ 3  6  7]
 [ 1  6 11]
 [ 2  5  8]]


In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return np.cumsum(A, axis=1)

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [6]:
import numpy as np

def encode(a):
    i, reps = 1, 1
    repetitions = []
    elements = []
    elements.append(a[0])
    while (i < len(a)):
        if (a[i] == a[i - 1]):
            reps += 1
        else:
            elements.append(a[i])
            repetitions.append(reps)
            reps = 1
        i += 1
    repetitions.append(reps)
    return elements, repetitions
            
    

a = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
print (a)
encode(a)

[1 2 2 3 3 1 1 5 5 2 3 3]


([1, 2, 3, 1, 5, 2, 3], [1, 2, 2, 2, 2, 1, 2])

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

[1 2 3 1 5 2 3] [1. 2. 2. 2. 2. 1. 2.]
CPU times: user 699 µs, sys: 935 µs, total: 1.63 ms
Wall time: 1.24 ms


### Задание 6

Задан двумерный массив $X$. Для каждой строчки массива $X$ необходимо сделать следующее преобразование.

Пусть дана строчка $x$. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (значение по умолчанию $a$=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив $x$ с преобразованным $x$ и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива $X$. Массив $X$ при этом должен остаться без изменений.


Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [42]:
import numpy as np
X = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

def transform(X, a=1):
    Y = []
    for i in range(len(X)):
        res = []
        for j in range(len(X[0])):
            if (j % 2 == 1):
                res.append(a)
            else:
                res.append(X[i][j] ** 3)
        res.reverse()
        Y.append(list(X[i]) + res)
    return (np.array(Y))
Y = transform(X)
print (X)
print (Y)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[   1    2    3    4    5  125    1   27    1    1]
 [   6    7    8    9   10 1000    1  512    1  216]]
